### ISSUE TITLE
Building news engine

### ISSUE THREAD

**Issue by firmai** [JMMackenzie/CC-News-Tools#4]
Hi @JMMackenzie I came accross your paper and I am looking at a way to build a news database that updates every day, is this something you can help me with? I am very happy to cover the costs to get this off the ground. 

Cheers,
Derek

**Comment by JMMackenzie** [comment]
Hello!

Sorry for the late response, I had somehow missed this.
I currently do not have cycles to help with this idea, sorry about that. But the common crawl news stream does have daily updates, so you'd realistically just need to plug into that and collect documents that align with your goals (easier said than done, but not impossible!)

If you need any further assistance please reach out to me here or via email at joel.mackenzie@uq.edu.au

Cheers!
