### ISSUE TITLE
Updated version of dataset?

### ISSUE THREAD

**Issue by AngledLuffa** [JMMackenzie/CC-News-Tools#5]
Hi,

Thanks for providing these tools.  We are looking to build an updated version of some transformers as part of Stanford's Stanza project.  This repo will be very useful in terms of building an updated version of the cc-news-en dataset.

Before we start doing that, it woukd be worth asking: have any of the future works from the paper been implemented, or is there a version of the dataset with data more recent than 2018?

Thanks!

**Comment by JMMackenzie** [comment]
Hello,

No active work on this currently, sorry. If you're looking for large-scale web data (apart from the Common Crawl), there is a new ClueWeb collection from CMU/Microsoft: http://lemurproject.org/clueweb22/

Cheers!

**Comment by AngledLuffa** [comment]
Thanks for the update!  Time to put in the work, I suppose
