### ISSUE TITLE
Convenient way to download all files?

### ISSUE THREAD

**Issue by AngledLuffa** [JMMackenzie/CC-News-Tools#6]
Hi again!

I found a cloudstor with the EN news:

https://cloudstor.aarnet.edu.au/plus/s/M8BvXxe6faLZ4uE?path=%2Fwarc

However, it is not particularly easy to download them all at once onto my work Linux cluster from there.  At least, I haven't found an easy way to do it.  Is there a convenient way to do so?

Thanks

**Comment by AngledLuffa** [comment]
Never mind!  I see get_warc.sh loops over all the files.  Thanks for providing that

**Comment by JMMackenzie** [comment]
No worries. Cloudstor is being decommissioned at the end of the year, so I will need to do something else with the data soon. Any suggestions are most welcome!
